### ISSUE TITLE
Login id and password for live demo?

### ISSUE THREAD

**Issue by BaaridunNasr** [ONE-F-M/One-FM#2214]

**Comment by mymi14s** [comment]
@PhantomKunai we do not have a live demo, you can install the app on your machine for testing.

**Comment by BaaridunNasr** [comment]
https://dev.one-fm.com/

https://github.com/ONE-F-M/One-FM#live-demo

@mymi14s 

This is where I found the information.

**Comment by mymi14s** [comment]
Oh sorry, the links are not for demo, we will update the spaces soon.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BaaridunNasr** [comment]
Ah okay, no worries. Thank you for the information.
